### ISSUE TITLE
Installing additional packages (insightface)

### ISSUE THREAD

**Issue by germyparker** [pinokiofactory/stable-diffusion-webui-forge#3]
What's the best way to install additional python modules?  I attempted to use Forge's built in ControlNet IP-Adapter, and got the error: 

```
ModuleNotFoundError: No module named 'insightface'
```
This is on MacOS / apple silicon, idk if that makes any difference.  Here are the full error details:

```
Loading Model: {'checkpoint_info': {'filename': '[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/models/Stable-diffusion/boltningRealistic_hyperD.safetensors', 'hash': 'eeb78611'}, 'additional_modules': ['[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/models/VAE/xlVAEC_f1.safetensors'], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for mps with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 196, 'text_encoder_2': 518, 'ignore': 0}

Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 9.0s (unload existing model: 0.1s, forge model load: 8.8s).
2024-10-06 17:08:20,621 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-10-06 17:08:20,638 - ControlNet - INFO - Using preprocessor: InsightFace+CLIP-H (IPAdapter)
2024-10-06 17:08:20,638 - ControlNet - INFO - preprocessor resolution = 0.5
*** Error running process: [/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_ipadapter/lib_ipadapter/IPAdapterPlus.py", line 566, in load_insight_face
        from insightface.app import FaceAnalysis
    ModuleNotFoundError: No module named 'insightface'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/modules/scripts.py", line 844, in process
        script.process(p, *script_args)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 554, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 328, in process_unit_after_click_generate
        preprocessor_output = preprocessor(
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_ipadapter/scripts/forge_ipadapter.py", line 46, in __call__
        insightface=self.load_insightface(),
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_ipadapter/scripts/forge_ipadapter.py", line 40, in load_insightface
        self.cached_insightface = opInsightFaceLoader()[0]
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_ipadapter/lib_ipadapter/IPAdapterPlus.py", line 568, in load_insight_face
        raise Exception(e)
    Exception: No module named 'insightface'

---
All loaded to GPU.
Moving model(s) has taken 0.01 seconds
*** Error running process_before_every_sampling: [/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/modules/scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 561, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
[Unload] Trying to free 9745.36 MB for mps with 0 models keep loaded ... Current free memory is 28938.62 MB ... Done.
All loaded to GPU.
Moving model(s) has taken 1.49 seconds
100%|####################################################################| 6/6 [00:15<00:00,  2.54s/it]
[Unload] Trying to free 9126.85 MB for mps with 0 models keep loaded ... Current free memory is 23473.66 MB ... Done.
All loaded to GPU.
Moving model(s) has taken 0.14 seconds
*** Error running postprocess_batch_list: [/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/modules/scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "[/path/to/]pinokio/api/stable-diffusion-webui-forge.git/app/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---

// then successful image generation stuff, but without the applied ip-adapter
```

This probably should install by default in the upstream Forge repo, but, that repo seems like they have a LOT of issues on their plate, so I thought it might be easier to handle from the Pinokio side.

**Comment by germyparker** [comment]
Ok solution found (thanks to Morpheus on the Pinokio discord).  Just go into the app directory and install insightface!

```
cd /path/to/pinokio/api/stable-diffusion-webui-forge.git/app
source venv/bin/activate
pip list 
# check to make sure some version of onnxruntime is installed
pip install insightface
```

I got some (apparently common) installation errors that weren't really related and did not interfere. Full success!
